{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | quote }}
type: Opaque
{{- if .Values.secret.stringdata }}
stringData:
  {{- range $key, $value := .Values.secret.stringdata }}
  {{ $key }}: {{ tpl $value $ | quote }}
  {{- end }}
{{- end }}
{{- if .Values.secret.data }}
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ tpl $value $ | quote }}
  {{- end }}
{{- end }}
{{- end }}