{{- if .Values.imagePullSecret.enabled }}
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoia3ViZS1kZXBsb3ktdG9rZW4iLCJwYXNzd29yZCI6ImtQNXNzWG1ac1B6Z0dxSkhwM3pSIiwiZW1haWwiOiJjaGFpdGFueWEuYW1pbkBnZXRrYXJtYS5jby51ayIsImF1dGgiOiJhM1ZpWlMxa1pYQnNiM2t0ZEc5clpXNDZhMUExYzNOWWJWcHpVSHBuUjNGS1NIQXplbEk9In19fQ==
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
type: kubernetes.io/dockerconfigjson
{{- end }}