{{- if .Values.external.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  PG_USER: {{ .Values.external.postgres.user | quote }}
  PG_PASSWORD: {{ .Values.external.postgres.password | quote  }}
  PG_HOST: {{ .Values.external.postgres.host | quote }}
  PG_PORT: {{ .Values.external.postgres.port | quote }}
  PG_DB: {{ .Values.external.postgres.db | quote }}
data:
  PG_CA: {{ .Values.external.postgres.cacert | quote }}
{{- end }}
