{{- if and .Values.ingress.externalcert.enabled (.Values.ingress.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tlssecretname | quote }}
type: kubernetes.io/tls
data:
  ca.crt: ""
  tls.crt: {{ .Values.ingress.externalcert.cert }}
  tls.key: {{ .Values.ingress.externalcert.key }}
{{- end }}  